repos:
  # linting & formatting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: '\.[jt]sx?$' # *.js, *.jsx, *.ts, *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "eslint"
          - "eslint-config-next"
          - "eslint-config-prettier"
          - "eslint-plugin-cypress"
          - "eslint-plugin-jest"
          - "eslint-plugin-react-hooks"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '\.[jt]sx?$' # *.js, *.jsx, *.ts, *.tsx
  # secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          - --exclude-files
          - .*test\.json
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
