repos:
  # linting & formatting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-beta.2
    hooks:
      - id: eslint
        files: '\.[jt]sx?$' # *.js, *.jsx, *.ts, *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "eslint"
          - "eslint-config-next"
          - "eslint-config-prettier"
          - "eslint-plugin-cypress"
          - "eslint-plugin-jest"
          - "eslint-plugin-react-hooks"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '\.[jt]sx?$' # *.js, *.jsx, *.ts, *.tsx
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
  # python formatting
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
  # secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          - --exclude-files
          - .yarn/*
  # terraform formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
