name: "Application Deploy"
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      deploy_frontend:
        type: boolean
        default: true
    secrets:
      DEPLOY_ROLE:
        required: true
  workflow_dispatch:
    inputs:
      target:
        required: true
        type: choice
        options:
          - stage
          - prod
jobs:
  lambda-deploy:
    name: "Frontend-Deploy"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: us-east-1
          role-session-name: GitHubAppDeploy
      - name: Update Frontend Lambda Code
        run: |
          aws lambda update-function-code \
          --function-name  ${{ inputs.target}}-frontend \
          --s3-bucket ${{ vars.artifact_bucket }} --s3-key $GITHUB_REF_NAME/frontend.zip
      
        