name: "Front End Deploy"
on:
  workflow_call:
  workflow_dispatch:
jobs:
  next-deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      ## Dummy step to clear up spurious pipeline failures
      - name: Dummy
        run: echo 'true'