name: "CICD Pipeline"
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  changes:
    name: "Check for changes"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform:
              - 'tf/**/*.tf'
              - 'tf/**/*.tfvars'
              - 'tf/**/*.tfbackend'
            app:
              - 'packages.json'
              - '.eslintrc.yaml'
              - '.codeclimate.yml'
              - 'src/app/**/*'
              - '**/*.ts'
              
            

  call-tf-validation:
    uses: ./.github/workflows/terraform-validate.yml
    needs: changes
    ## Skip if no changes in terraform files
    if: needs.changes.filter.outputs.terraform == 'true'
    strategy:
      matrix:
        project: [test]
    with:
      project: ${{ matrix.project }}
    name: Calling TF Validate

  call-app-lint:
    name: "Calling Application Lint Stage"
    uses: ./.github/workflows/app-lint.yml
    needs: changes
    if: needs.changes.filter.outputs.app == 'true'

  call-tf-plan:
    name: "Calling TF Plan Stage"
    ## Call terraform plan if pull request with terraform changes
    if: |
      github.event_name == 'pull_request' &&
      needs.changes.filter.outputs.terraform == 'true'
    uses: ./.github/workflows/terraform-plan.yml
    strategy:
      matrix:
        target: [stage, prod]
        project: [application]
    with:
      target: ${{ matrix.target }}
      project: ${{ matrix.project }}
    secrets:
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}
    permissions:
      id-token: write
      contents: read

  call-app-unit-testing:
    name: "Calling Unit Testing"
    uses: ./.github/workflows/app-unit-test.yml
    needs: changes
    if: needs.changes.filter.outputs.app == 'true'
    secrets:
      CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}
    permissions:
      id-token: write
      contents: read
      actions: read

  call-app-build:
    name: "Calling App Build Stage"
    uses: ./.github/workflows/app-build.yml
    needs: changes
    ## Always build on main. Build on others if changes
    if: |
      needs.changes.filter.outputs.app == 'true' ||
      (github.ref == 'refs/heads/main' && github.event_name == 'push')
    secrets:
      UPLOAD_ROLE: ${{ secrets.UPLOAD_ROLE }}
    ## If running on a protected branch, upload artifact with role in stage environment
    with:
      upload: ${{ github.ref_protected }}
      environment: ${{ github.ref_protected == true && 'stage' || '' }}
    permissions:
      id-token: write
      contents: read
    

  call-tf-deploy:
    name: "Calling TF Deploy Stage"
    needs: call-tf-validation
    ## Run if on main branch
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    uses: ./.github/workflows/terraform-deploy.yml
    strategy:
      matrix:
        project: [test, application]
    with:
      target: stage
      project: ${{ matrix.project }}
    secrets:
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}
    permissions:
      id-token: write
      contents: read
  
  call-app-deploy:
    name: "Calling App Deploy (Stage)"
    uses: ./.github/workflows/app-deploy.yml
    ## Run after terraform deploy and app build
    needs:
      - call-app-build
      - call-tf-deploy
    concurrency:
      group: stage-deployment
    ## Run if the any previous step succeed, none fail, and on main branch
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      contains(needs.*.result, 'succeess') &&
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    with:
      target: stage
    secrets:
      DEPLOY_ROLE: ${{ secrets.DEPLOY_ROLE }}
    permissions:
      id-token: write
      contents: read
  
  call-integration-testing:
    name: "Calling Application Integration Testing"
    uses: ./.github/workflows/app-int-test.yml
    ## Run after TF and Application deployments have finished
    needs:
      - call-app-deploy
      - call-tf-deploy
    ## If terraform or application deployments have succeeded, but one has been skipped, run anyways
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      contains(needs.*.result, 'success')
    concurrency:
      group: stage-deployment
    with:
      target: stage
    secrets:
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}


