name: "CICD Pipeline"
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  changes:
    name: "Check for changes"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform:
              - 'tf/**/*.tf'
              - 'tf/**/*.tfvars'
              - 'tf/**/*.tfbackend'
            typescript:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
              - '**/*.jsx'
            scss:
              - '**/*.scss'

  call-tf-validation:
    uses: ./.github/workflows/terraform-validate.yml
    needs: changes
    if: needs.changes.filter.outputs.terraform == 'true'
    strategy:
      matrix:
        project: [test]
    with:
      project: ${{ matrix.project }}
    name: Calling TF Validate

  call-app-lint:
    name: "Calling Application Lint Stage"
    uses: ./.github/workflows/app-lint.yml
    needs: changes
    if: needs.changes.filter.outputs.typescript == 'true' || needs.changes.filter.outputs.scss == 'true'

  call-tf-plan:
    name: "Calling TF Plan Stage"
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/terraform-plan.yml
    strategy:
      matrix:
        target: [stage, prod]
        project: [test]
    with:
      target: ${{ matrix.target }}
      project: ${{ matrix.project }}
    secrets:
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}
    permissions:
      id-token: write
      contents: read

  call-app-unit-testing:
    name: "Calling Unit Testing"
    uses: ./.github/workflows/app-unit-test.yml
    needs: changes
    if: needs.changes.filter.outputs.typescript == 'true' || needs.changes.filter.outputs.scss == 'true'
    secrets:
      CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}
    permissions:
      id-token: write
      contents: read
      actions: read

  call-app-build:
    name: "Calling App Build Stage"
    uses: ./.github/workflows/app-build.yml
    needs: call-app-lint
    secrets:
      UPLOAD_ROLE: ${{ secrets.UPLOAD_ROLE }}
    with:
      upload: ${{ github.ref_protected }}
      environment: ${{ github.ref_protected == true && 'stage' || '' }}
    permissions:
      id-token: write
      contents: read
    

  call-tf-deploy:
    name: "Calling TF Deploy Stage"
    needs: call-tf-validation
    # Fix before merging!!!
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      github.ref == 'refs/heads/issue/front-end-infra' &&
      github.event_name == 'push'
    uses: ./.github/workflows/terraform-deploy.yml
    strategy:
      matrix:
        project: [test]
    with:
      target: stage
      project: ${{ matrix.project }}
    secrets:
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}
    permissions:
      id-token: write
      contents: read

  get-tf-output:
    name: "Get Terraform Output (Stage)"
    needs:
      - call-tf-deploy
    if: |
      always() &&
      !contains(needs.*.result, 'failure')
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: validation
    strategy:
      matrix:
        project: ['test','application']
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ROLE }}
          aws-region: us-east-1
          role-session-name: GitHubTFDeployment
      
      - name: Terraform Init
        working-directory: tf/projects/${{ matrix.project }}
        run: terraform init -backend-config=env/stage.s3.tfbackend -reconfigure
      - name: Terraform Output
        working-directory: tf/projects/${{ matrix.project }}
        id: values
        run: |
          terraform output | sed -r  -e 's|(.*) = "(.*)"|${{ matrix.project }}_\1=\2|' | grep '^[a-z].*' || true >> $GITHUB_OUTPUT

  
  call-app-deploy:
    name: "Calling App Deploy (Stage)"
    uses: ./.github/workflows/app-deploy.yml
    needs:
      - call-app-build
      - call-tf-deploy
    concurrency:
      group: stage-deployment
    ## Fix before merging
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      github.ref == 'refs/heads/issue/front-end-infra' &&
      github.event_name == 'push'
    with:
      target: stage
    secrets:
      DEPLOY_ROLE: ${{ secrets.DEPLOY_ROLE }}
    permissions:
      id-token: write
      contents: read
  
  call-integration-testing:
    name: "Calling Application Integration Testing"
    uses: ./.github/workflows/app-int-test.yml
    needs:
      - call-app-deploy
      - get-tf-output
    if: |
      always() &&
      !contains(needs.*.result, 'failure')
    concurrency:
      group: stage-deployment
    with:
      application_endpoint: ${{ needs.get-tf-output.values.outputs.application_cloudfront_url }}


