name: "Deploy All"
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      TERRAFORM_ROLE:
        required: true
      DEPLOY_ROLE:
        required: true
  workflow_dispatch:
    inputs:
      target:
        required: true
        type: choice
        options:
          - stage
          - prod
          - test

jobs:
  call-tf-deploy:
    name: "Calling Terraform Deploy (${{ inputs.target }})"
    uses: ./.github/workflows/terraform-deploy.yml
    strategy:
      matrix:
        project: [data,application,monitoring]
    with:
      target: ${{ inputs.target }}
      project: ${{ matrix.project }}
    secrets:
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}
    permissions:
      id-token: write
      contents: read
  call-app-deploy:
    name: "Calling App Deploy (${{ inputs.target }})"
    uses: ./.github/workflows/app-deploy.yml
    ## Run after terraform deploy and app build
    needs:
      - call-tf-deploy
    concurrency:
      group: ${{ inputs.target }}-deployment
    with:
      target: ${{ inputs.target }}
    secrets:
      DEPLOY_ROLE: ${{ secrets.DEPLOY_ROLE }}
    permissions:
      id-token: write
      contents: read
